[package]
name = "easyhotkeys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cli-clipboard = "0.4.0"
clipboard-ext = "0.2.0"
deno_task_shell = { version = "0.8.2", features = [
    "serde",
    "serialization"
], git = "https://github.com/Tricked-dev/deno_task_shell", rev = "59e72b67566444152a0fbe963235424d8b52c954" }
mlua = { version = "0.8", features = [
    "lua54",
    "vendored",
    "parking_lot",
    "async",
    "serde",
    "serialize",
    "mlua_derive",
    "macros"
] }
once_cell = { version = "1.17.0", features = ["parking_lot"] }
rdev = { version = "0.5.2", features = ["serde", "serialize"] }
rust-embed = "6.4.2"
screenshots = "0.4.6"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = [
    "rt",
    "macros",
    "rt-multi-thread",
    "sync",
    "parking_lot",
    "time",
    "fs"
] }
tokio-util = { version = "0.7.4" }
os_pipe = { version = "1.0.1" }
rodio = { version = "0.16.0" }
notify-rust = "4"
